<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace GPBMetadata;

class Grpc
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa8010a0a677270632e70726f746f120a68656c6c6f776f726c64221c0a" .
            "0c48656c6c6f52657175657374120c0a046e616d65180120012809221d0a" .
            "0a48656c6c6f5265706c79120f0a076d6573736167651801200128093249" .
            "0a0747726565746572123e0a0853617948656c6c6f12182e68656c6c6f77" .
            "6f726c642e48656c6c6f526571756573741a162e68656c6c6f776f726c64" .
            "2e48656c6c6f5265706c792200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

