<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>helloworld.ArrayDataResponse</code>
 */
class ArrayDataResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 max_client = 1;</code>
     */
    private $max_client = 0;
    /**
     * Generated from protobuf field <code>int32 max_sum = 2;</code>
     */
    private $max_sum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_client
     *     @type int $max_sum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 max_client = 1;</code>
     * @return int
     */
    public function getMaxClient()
    {
        return $this->max_client;
    }

    /**
     * Generated from protobuf field <code>int32 max_client = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxClient($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_client = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_sum = 2;</code>
     * @return int
     */
    public function getMaxSum()
    {
        return $this->max_sum;
    }

    /**
     * Generated from protobuf field <code>int32 max_sum = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxSum($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_sum = $var;

        return $this;
    }

}

