<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc.proto

namespace Helloworld;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>helloworld.DeliveryDataRequest</code>
 */
class DeliveryDataRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 coef = 1;</code>
     */
    private $coef = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $coef
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Grpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 coef = 1;</code>
     * @return int
     */
    public function getCoef()
    {
        return $this->coef;
    }

    /**
     * Generated from protobuf field <code>int32 coef = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCoef($var)
    {
        GPBUtil::checkInt32($var);
        $this->coef = $var;

        return $this;
    }

}

